services:
  mysql:
    image: mysql:8.0
    container_name: spring-batch-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: source_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/main/resources/schema-mysql.sql:/docker-entrypoint-initdb.d/schema.sql

  postgres:
    image: postgres:15
    container_name: spring-batch-postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: target_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/schema-postgresql.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  mysql_data:
  postgres_data:
