services:
  mysql:
    image: mysql:latest
    container_name: spring-batch-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: source_db
    ports:
      - "3306:3306"
    volumes:
      - ./src/main/resources/schema-mysql.sql:/docker-entrypoint-initdb.d/schema.sql

  postgres:
    image: postgres:latest
    container_name: spring-batch-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: target_db
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/schema-postgresql.sql:/docker-entrypoint-initdb.d/schema.sql
