spring:
  application:
    name: spring-batch-showcase

  datasource:
    # MySQL datasource (source database)
    mysql:
      url: jdbc:mysql://localhost:3306/source_db?useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: password

    # PostgreSQL datasource (target database)
    postgresql:
      url: jdbc:postgresql://localhost:5432/target_db
      username: postgres
      password: password

    # H2 for Spring Batch metadata
    url: jdbc:h2:mem:batch_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  batch:
    job:
      enabled: false # Prevent automatic job execution on startup
    jdbc:
      initialize-schema: always

logging:
  level:
    com.example.batch: DEBUG
    org.springframework.batch: INFO
    org.springframework.jdbc: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

